name: Install GoCD 25.2.0

on:
  push:
    branches:
      - main

jobs:
  install-gocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GoCD 25.2.0
        run: |
          curl -fsSL 'https://www.gocd.org/test-drive-gocd/try.sh' | bash -s 'https://download.gocd.org/test-drive/installers/25.2.0/20485/gocd-25.2.0-20485-3638-linux.zip'
