jobs:
  check_tabby_files:
    runs-on: ubuntu-latest

    steps:
      - name: Download tabby zip
        run: |
          curl -L -o tabby.zip https://your-url/tabby-1.0.223-macos-x86_64.zip

      - name: Calculate SHA512 checksum (base64)
        run: |
          actual_sha512=$(openssl dgst -sha512 -binary tabby.zip | base64)
          echo "$actual_sha512" > actual_sha512.txt
          echo "Actual SHA512: $actual_sha512"

      - name: Verify SHA512 checksum
        run: |
          expected_sha512="+6/4M2joeNsSY91t8QRIn3/EqUTBZx5hdEYCHjP0KQRagUhzeDHpGItsRbzLaSoVNWSaavpm+duo0/Hd5kQdDg=="
          actual_sha512=$(cat actual_sha512.txt)
          echo "Expected: $expected_sha512"
          echo "Actual:   $actual_sha512"
          if [ "$actual_sha512" != "$expected_sha512" ]; then
            echo "❌ SHA512 checksum mismatch!"
            exit 1
          fi
          echo "✅ SHA512 checksum matched."
