version: 1.0.223
files:
  - url: tabby-1.0.223-macos-x86_64.zip
    sha512: +6/4M2joeNsSY91t8QRIn3/EqUTBZx5hdEYCHjP0KQRagUhzeDHpGItsRbzLaSoVNWSaavpm+duo0/Hd5kQdDg==
  - url: tabby-1.0.223-macos-x86_64.dmg
    sha512: YgNRfiMNOZgLc8CdBQnQv2XJJxZtxTqkHedTB3yqhyih3c544qTZ4v8BuzUA2tdCsKLfIFgavQNEbxYV8qejEg==
    size: 143143377
  - url: tabby-1.0.223-macos-x86_64.dmg
    sha512: YgNRfiMNOZgLc8CdBQnQv2XJJxZtxTqkHedTB3yqhyih3c544qTZ4v8BuzUA2tdCsKLfIFgavQNEbxYV8qejEg==
    size: 143143377
path: tabby-1.0.223-macos-x86_64.zip
sha512: +6/4M2joeNsSY91t8QRIn3/EqUTBZx5hdEYCHjP0KQRagUhzeDHpGItsRbzLaSoVNWSaavpm+duo0/Hd5kQdDg==
releaseDate: '2025-03-12T10:27:26.066Z'
